"""
SynoDB Loader

Loads seed queries from semantic.yaml into DynamoDB with embeddings.
"""

import boto3
import hashlib
import json
from datetime import datetime
from typing import List, Dict, Any, Optional
from botocore.exceptions import ClientError

from shared.schemas.unified_metadata import UnifiedMetadataGraph
from shared.embeddings.titan_client import TitanEmbeddingsClient


class SynoDBLoader:
    """Load queries into SynoDB (DynamoDB)."""

    def __init__(
        self,
        table_name: str = 'synodb_queries',
        region: str = 'us-east-1'
    ):
        """
        Initialize SynoDB loader.

        Args:
            table_name: DynamoDB table name
            region: AWS region
        """
        self.table_name = table_name
        self.region = region
        self.dynamodb = boto3.resource('dynamodb', region_name=region)
        self.table = self.dynamodb.Table(table_name)
        self.titan = TitanEmbeddingsClient(region=region)

    def load_seed_queries(
        self,
        metadata: UnifiedMetadataGraph,
        workload: str,
        verbose: bool = False
    ) -> int:
        """
        Load seed queries from metadata graph into DynamoDB.

        Args:
            metadata: Unified metadata graph (with embeddings)
            workload: Workload name
            verbose: Print progress

        Returns:
            Number of queries loaded

        Example:
            >>> from shared.metadata.combiner import combine_metadata
            >>> from shared.embeddings.metadata_embedder import embed_metadata
            >>> graph = combine_metadata("financial_portfolios", "financial_portfolios_db")
            >>> embedded_graph = embed_metadata(graph)
            >>> loader = SynoDBLoader()
            >>> count = loader.load_seed_queries(embedded_graph, "financial_portfolios")
            >>> count > 0
            True
        """
        query_count = 0

        for table in metadata.tables:
            for query in table.seed_queries:
                try:
                    self._load_query(
                        query=query,
                        workload=workload,
                        table_name=table.name
                    )
                    query_count += 1

                    if verbose:
                        print(f"Loaded query: {query.get('question', '')[:50]}...")

                except Exception as e:
                    print(f"Warning: Failed to load query: {e}")
                    continue

        if verbose:
            print(f"Loaded {query_count} seed queries for workload '{workload}'")

        return query_count

    def _load_query(
        self,
        query: Dict[str, Any],
        workload: str,
        table_name: str
    ):
        """
        Load a single query into DynamoDB.

        Args:
            query: Query dict with 'question', 'sql', 'explanation', 'embedding'
            workload: Workload name
            table_name: Source table name
        """
        question = query.get('question', '')
        sql = query.get('sql', '')

        if not question or not sql:
            raise ValueError("Query must have 'question' and 'sql' fields")

        # Generate query_id (hash of question)
        query_id = self._generate_query_id(question)

        # Extract tables used from SQL (simple regex)
        tables_used = self._extract_tables_from_sql(sql)

        # Get or generate embedding
        embedding = query.get('embedding')
        if not embedding:
            # Generate embedding if not already present
            embedding = self.titan.generate_embedding(f"question: {question}. SQL: {sql[:500]}")

        # Convert embedding to binary for storage
        embedding_bytes = json.dumps(embedding).encode('utf-8')

        # Prepare item
        item = {
            'query_id': query_id,
            'workload': workload,
            'nl_text': question,
            'sql': sql,
            'explanation': query.get('explanation', ''),
            'source_table': table_name,
            'tables_used': tables_used,
            'query_type': 'seed',  # 'seed' or 'learned'
            'success_count': 0,
            'last_used': None,
            'embedding': embedding_bytes,
            'created_at': datetime.utcnow().isoformat()
        }

        # Store in DynamoDB
        self.table.put_item(Item=item)

    def save_learned_query(
        self,
        nl_query: str,
        sql: str,
        workload: str,
        tables_used: List[str],
        success: bool = True,
        execution_time_ms: Optional[int] = None
    ) -> str:
        """
        Save a learned query (generated by Analysis Agent).

        Args:
            nl_query: Natural language query
            sql: Generated SQL
            workload: Workload name
            tables_used: List of tables used in query
            success: Whether query executed successfully
            execution_time_ms: Query execution time

        Returns:
            query_id

        Example:
            >>> loader = SynoDBLoader()
            >>> query_id = loader.save_learned_query(
            ...     "What is total revenue?",
            ...     "SELECT SUM(revenue) FROM sales",
            ...     "financial_portfolios",
            ...     ["sales"]
            ... )
        """
        query_id = self._generate_query_id(nl_query)

        # Generate embedding
        embedding = self.titan.generate_embedding(f"question: {nl_query}. SQL: {sql[:500]}")
        embedding_bytes = json.dumps(embedding).encode('utf-8')

        # Check if query already exists
        try:
            response = self.table.get_item(
                Key={'query_id': query_id, 'workload': workload}
            )

            if 'Item' in response:
                # Update existing query (increment success count)
                item = response['Item']
                success_count = item.get('success_count', 0)

                self.table.update_item(
                    Key={'query_id': query_id, 'workload': workload},
                    UpdateExpression='SET success_count = :count, last_used = :time',
                    ExpressionAttributeValues={
                        ':count': success_count + (1 if success else 0),
                        ':time': datetime.utcnow().isoformat()
                    }
                )

                return query_id

        except ClientError:
            pass

        # Create new query
        item = {
            'query_id': query_id,
            'workload': workload,
            'nl_text': nl_query,
            'sql': sql,
            'tables_used': tables_used,
            'query_type': 'learned',
            'success_count': 1 if success else 0,
            'last_used': datetime.utcnow().isoformat(),
            'execution_time_ms': execution_time_ms,
            'embedding': embedding_bytes,
            'created_at': datetime.utcnow().isoformat()
        }

        self.table.put_item(Item=item)
        return query_id

    def _generate_query_id(self, question: str) -> str:
        """
        Generate deterministic query ID from question text.

        Args:
            question: Natural language question

        Returns:
            Query ID (MD5 hash prefix)
        """
        hash_obj = hashlib.md5(question.lower().strip().encode('utf-8'))
        return f"query_{hash_obj.hexdigest()[:16]}"

    def _extract_tables_from_sql(self, sql: str) -> List[str]:
        """
        Extract table names from SQL (simple heuristic).

        Args:
            sql: SQL query

        Returns:
            List of table names

        Note: This is a simple regex-based extraction. For production,
        consider using a SQL parser like sqlparse.
        """
        import re

        # Remove comments
        sql = re.sub(r'--.*$', '', sql, flags=re.MULTILINE)
        sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)

        # Find patterns: FROM table, JOIN table
        patterns = [
            r'\bFROM\s+([a-zA-Z0-9_\.]+)',
            r'\bJOIN\s+([a-zA-Z0-9_\.]+)'
        ]

        tables = set()
        for pattern in patterns:
            matches = re.findall(pattern, sql, re.IGNORECASE)
            for match in matches:
                # Extract table name (remove database/schema prefix if present)
                table = match.split('.')[-1]
                tables.add(table)

        return list(tables)


def load_seed_queries(
    metadata: UnifiedMetadataGraph,
    workload: str,
    table_name: str = 'synodb_queries',
    region: str = 'us-east-1',
    verbose: bool = False
) -> int:
    """
    Convenience function to load seed queries.

    Args:
        metadata: Unified metadata graph
        workload: Workload name
        table_name: DynamoDB table name
        region: AWS region
        verbose: Print progress

    Returns:
        Number of queries loaded

    Example:
        >>> from shared.metadata.combiner import combine_metadata
        >>> from shared.embeddings.metadata_embedder import embed_metadata
        >>> graph = combine_metadata("financial_portfolios", "financial_portfolios_db")
        >>> embedded_graph = embed_metadata(graph)
        >>> count = load_seed_queries(embedded_graph, "financial_portfolios", verbose=True)
    """
    loader = SynoDBLoader(table_name=table_name, region=region)
    return loader.load_seed_queries(metadata, workload, verbose=verbose)
