"""
Unit tests for daily_sales metadata configuration files.
Generated by Metadata Agent on 2026-03-18.

Validates:
- All 5 config files exist and are valid YAML
- source.yaml schema and required keys
- semantic.yaml column roles, PII flags, aggregation semantics
- transformations.yaml cleaning rules and Gold star schema
- quality_rules.yaml thresholds and rule coverage
- schedule.yaml frequency and timing
"""

import os
import yaml
import pytest
from pathlib import Path


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

CONFIG_DIR = Path(__file__).resolve().parent.parent.parent / "config"


def _load_yaml(filename: str) -> dict:
    """Load and parse a YAML config file."""
    filepath = CONFIG_DIR / filename
    with open(filepath, "r") as f:
        return yaml.safe_load(f)


@pytest.fixture(scope="module")
def source_config():
    return _load_yaml("source.yaml")


@pytest.fixture(scope="module")
def semantic_config():
    return _load_yaml("semantic.yaml")


@pytest.fixture(scope="module")
def transformations_config():
    return _load_yaml("transformations.yaml")


@pytest.fixture(scope="module")
def quality_config():
    return _load_yaml("quality_rules.yaml")


@pytest.fixture(scope="module")
def schedule_config():
    return _load_yaml("schedule.yaml")


# ---------------------------------------------------------------------------
# 1. File existence and YAML validity (5 tests)
# ---------------------------------------------------------------------------

class TestConfigFilesExist:
    """All 5 config files must exist and be parseable YAML."""

    @pytest.mark.parametrize("filename", [
        "source.yaml",
        "semantic.yaml",
        "transformations.yaml",
        "quality_rules.yaml",
        "schedule.yaml",
    ])
    def test_config_file_exists(self, filename):
        filepath = CONFIG_DIR / filename
        assert filepath.exists(), f"{filename} does not exist at {CONFIG_DIR}"

    @pytest.mark.parametrize("filename", [
        "source.yaml",
        "semantic.yaml",
        "transformations.yaml",
        "quality_rules.yaml",
        "schedule.yaml",
    ])
    def test_config_file_is_valid_yaml(self, filename):
        data = _load_yaml(filename)
        assert isinstance(data, dict), f"{filename} did not parse to a dict"


# ---------------------------------------------------------------------------
# 2. source.yaml tests (15 tests)
# ---------------------------------------------------------------------------

class TestSourceConfig:
    """Validate source.yaml structure and content."""

    def test_has_source_key(self, source_config):
        assert "source" in source_config

    def test_source_name(self, source_config):
        assert source_config["source"]["name"] == "daily_sales"

    def test_source_format_csv(self, source_config):
        assert source_config["source"]["format"] == "csv"

    def test_source_location_is_s3(self, source_config):
        loc = source_config["source"]["location"]
        assert loc.startswith("s3://"), "Location must be an S3 path"

    def test_no_hardcoded_account_id(self, source_config):
        """Security: no AWS account IDs in source config."""
        raw = yaml.dump(source_config)
        # AWS account IDs are 12-digit numbers
        import re
        matches = re.findall(r"\b\d{12}\b", raw)
        assert len(matches) == 0, f"Found potential AWS account ID: {matches}"

    def test_connection_id_not_hardcoded_secret(self, source_config):
        conn = source_config["source"].get("connection_id", "")
        assert "AKIA" not in conn, "Connection ID must not contain AWS access keys"

    def test_primary_key_defined(self, source_config):
        pk = source_config["source"]["primary_key"]
        assert isinstance(pk, list)
        assert "sale_id" in pk

    def test_schema_has_columns(self, source_config):
        columns = source_config["source"]["schema"]["columns"]
        assert isinstance(columns, list)

    def test_schema_has_15_columns(self, source_config):
        columns = source_config["source"]["schema"]["columns"]
        assert len(columns) == 15, f"Expected 15 columns, got {len(columns)}"

    def test_all_columns_have_name_and_type(self, source_config):
        columns = source_config["source"]["schema"]["columns"]
        for col in columns:
            assert "name" in col, f"Column missing 'name': {col}"
            assert "type" in col, f"Column {col['name']} missing 'type'"

    def test_expected_column_names(self, source_config):
        columns = source_config["source"]["schema"]["columns"]
        names = {c["name"] for c in columns}
        expected = {
            "sale_id", "sale_date", "store_id", "store_name",
            "customer_name", "customer_email", "product_sku", "product_name",
            "category", "quantity", "unit_price", "discount_pct",
            "total_amount", "payment_method", "region",
        }
        assert names == expected, f"Missing: {expected - names}, Extra: {names - expected}"

    def test_sale_id_not_nullable(self, source_config):
        columns = source_config["source"]["schema"]["columns"]
        sale_id = next(c for c in columns if c["name"] == "sale_id")
        assert sale_id.get("nullable") is False

    def test_zones_defined(self, source_config):
        zones = source_config["source"]["zones"]
        assert "bronze" in zones
        assert "silver" in zones
        assert "gold" in zones

    def test_silver_zone_is_iceberg(self, source_config):
        silver = source_config["source"]["zones"]["silver"]
        assert silver["format"] == "iceberg"

    def test_gold_zone_has_star_schema_tables(self, source_config):
        gold = source_config["source"]["zones"]["gold"]
        tables = gold.get("tables", [])
        assert "fact_sales" in tables
        assert "dim_store" in tables
        assert "dim_product" in tables
        assert "dim_date" in tables


# ---------------------------------------------------------------------------
# 3. semantic.yaml tests (16 tests)
# ---------------------------------------------------------------------------

class TestSemanticConfig:
    """Validate semantic.yaml column roles, PII, and business context."""

    def test_has_semantic_key(self, semantic_config):
        assert "semantic" in semantic_config

    def test_workload_name(self, semantic_config):
        assert semantic_config["semantic"]["workload"] == "daily_sales"

    def test_grain_defined(self, semantic_config):
        grain = semantic_config["semantic"]["grain"]
        assert "sale_id" in grain["grain_columns"]
        assert "sale_date" in grain["grain_columns"]

    def test_columns_defined(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        assert isinstance(columns, list)
        assert len(columns) == 15

    def test_every_column_has_role(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        valid_roles = {"identifier", "temporal", "dimension", "measure"}
        for col in columns:
            assert "role" in col, f"Column {col['name']} missing role"
            assert col["role"] in valid_roles, f"Column {col['name']} has invalid role: {col['role']}"

    def test_measure_columns_have_default_aggregation(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        measures = [c for c in columns if c["role"] == "measure"]
        assert len(measures) == 4, f"Expected 4 measures, got {len(measures)}"
        for m in measures:
            assert "default_aggregation" in m, f"Measure {m['name']} missing default_aggregation"

    def test_quantity_aggregation_is_sum(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        qty = next(c for c in columns if c["name"] == "quantity")
        assert qty["default_aggregation"] == "SUM"

    def test_unit_price_aggregation_is_avg(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        up = next(c for c in columns if c["name"] == "unit_price")
        assert up["default_aggregation"] == "AVG"

    def test_discount_pct_aggregation_is_avg(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        dp = next(c for c in columns if c["name"] == "discount_pct")
        assert dp["default_aggregation"] == "AVG"

    def test_total_amount_aggregation_is_sum(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        ta = next(c for c in columns if c["name"] == "total_amount")
        assert ta["default_aggregation"] == "SUM"

    def test_customer_name_pii_flagged(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        cn = next(c for c in columns if c["name"] == "customer_name")
        assert cn["pii"] is True
        assert cn["pii_type"] == "NAME"
        assert cn["pii_sensitivity"] == "MEDIUM"

    def test_customer_email_pii_flagged(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        ce = next(c for c in columns if c["name"] == "customer_email")
        assert ce["pii"] is True
        assert ce["pii_type"] == "EMAIL"
        assert ce["pii_sensitivity"] == "HIGH"

    def test_non_pii_columns_not_flagged(self, semantic_config):
        columns = semantic_config["semantic"]["columns"]
        non_pii = [c for c in columns if c["name"] not in ("customer_name", "customer_email")]
        for col in non_pii:
            assert col.get("pii") is False, f"Column {col['name']} should not be PII"

    def test_business_terms_defined(self, semantic_config):
        terms = semantic_config["semantic"]["business_terms"]
        term_names = {t["term"] for t in terms}
        assert "revenue" in term_names
        assert "average order value" in term_names

    def test_revenue_term_has_synonyms(self, semantic_config):
        terms = semantic_config["semantic"]["business_terms"]
        revenue = next(t for t in terms if t["term"] == "revenue")
        assert "sales" in revenue["synonyms"]
        assert "turnover" in revenue["synonyms"]

    def test_dimension_hierarchies_defined(self, semantic_config):
        hierarchies = semantic_config["semantic"]["dimension_hierarchies"]
        hierarchy_names = {h["name"] for h in hierarchies}
        assert "geography" in hierarchy_names
        assert "product" in hierarchy_names

    def test_lf_tags_defined_for_pii(self, semantic_config):
        assignments = semantic_config["semantic"]["lf_tag_assignments"]
        tagged_columns = {a["column"] for a in assignments}
        assert "customer_name" in tagged_columns
        assert "customer_email" in tagged_columns


# ---------------------------------------------------------------------------
# 4. transformations.yaml tests (12 tests)
# ---------------------------------------------------------------------------

class TestTransformationsConfig:
    """Validate transformation rules for Bronze->Silver and Silver->Gold."""

    def test_has_transformations_key(self, transformations_config):
        assert "transformations" in transformations_config

    def test_bronze_to_silver_defined(self, transformations_config):
        assert "bronze_to_silver" in transformations_config["transformations"]

    def test_dedup_on_sale_id(self, transformations_config):
        dedup = transformations_config["transformations"]["bronze_to_silver"]["deduplication"]
        assert dedup["enabled"] is True
        assert "sale_id" in dedup["key_columns"]

    def test_null_handling_customer_email(self, transformations_config):
        rules = transformations_config["transformations"]["bronze_to_silver"]["null_handling"]["rules"]
        email_rule = next(r for r in rules if r["column"] == "customer_email")
        assert email_rule["default_value"] == "unknown@masked.invalid"

    def test_type_casting_rules(self, transformations_config):
        rules = transformations_config["transformations"]["bronze_to_silver"]["type_casting"]["rules"]
        cast_map = {r["column"]: r["target_type"] for r in rules}
        assert cast_map["quantity"] == "integer"
        assert cast_map["unit_price"] == "float"
        assert cast_map["discount_pct"] == "float"
        assert cast_map["total_amount"] == "float"

    def test_validation_rules_exist(self, transformations_config):
        rules = transformations_config["transformations"]["bronze_to_silver"]["validation"]["rules"]
        rule_names = {r["name"] for r in rules}
        assert "discount_pct_range" in rule_names
        assert "quantity_positive" in rule_names
        assert "total_amount_positive" in rule_names

    def test_pii_masking_rules(self, transformations_config):
        rules = transformations_config["transformations"]["bronze_to_silver"]["pii_masking"]["rules"]
        masked_cols = {r["column"]: r["strategy"] for r in rules}
        assert masked_cols["customer_email"] == "hash"
        assert masked_cols["customer_name"] == "mask"

    def test_quarantine_enabled(self, transformations_config):
        quarantine = transformations_config["transformations"]["bronze_to_silver"]["quarantine"]
        assert quarantine["enabled"] is True

    def test_silver_to_gold_defined(self, transformations_config):
        assert "silver_to_gold" in transformations_config["transformations"]

    def test_gold_format_is_star_schema(self, transformations_config):
        gold = transformations_config["transformations"]["silver_to_gold"]
        assert gold["gold_format"] == "star_schema"

    def test_fact_table_defined(self, transformations_config):
        gold = transformations_config["transformations"]["silver_to_gold"]
        fact_names = [f["name"] for f in gold["fact_tables"]]
        assert "fact_sales" in fact_names

    def test_dimension_tables_defined(self, transformations_config):
        gold = transformations_config["transformations"]["silver_to_gold"]
        dim_names = {d["name"] for d in gold["dimension_tables"]}
        assert "dim_store" in dim_names
        assert "dim_product" in dim_names
        assert "dim_date" in dim_names


# ---------------------------------------------------------------------------
# 5. quality_rules.yaml tests (12 tests)
# ---------------------------------------------------------------------------

class TestQualityRulesConfig:
    """Validate quality rules, thresholds, and dimension coverage."""

    def test_has_quality_key(self, quality_config):
        assert "quality" in quality_config

    def test_silver_threshold(self, quality_config):
        threshold = quality_config["quality"]["thresholds"]["silver"]["minimum_score"]
        assert threshold == 0.80

    def test_gold_threshold(self, quality_config):
        threshold = quality_config["quality"]["thresholds"]["gold"]["minimum_score"]
        assert threshold == 0.95

    def test_critical_rules_must_pass_silver(self, quality_config):
        assert quality_config["quality"]["thresholds"]["silver"]["critical_rules_must_pass"] is True

    def test_critical_rules_must_pass_gold(self, quality_config):
        assert quality_config["quality"]["thresholds"]["gold"]["critical_rules_must_pass"] is True

    def test_completeness_rules_exist(self, quality_config):
        rules = quality_config["quality"]["rules"]["completeness"]
        assert len(rules) >= 2
        names = {r["name"] for r in rules}
        assert "sale_id_not_null" in names
        assert "sale_date_not_null" in names

    def test_uniqueness_rules_exist(self, quality_config):
        rules = quality_config["quality"]["rules"]["uniqueness"]
        names = {r["name"] for r in rules}
        assert "sale_id_unique" in names

    def test_validity_rules_exist(self, quality_config):
        rules = quality_config["quality"]["rules"]["validity"]
        names = {r["name"] for r in rules}
        assert "discount_pct_range" in names
        assert "quantity_positive" in names
        assert "total_amount_positive" in names

    def test_consistency_rules_exist(self, quality_config):
        rules = quality_config["quality"]["rules"]["consistency"]
        names = {r["name"] for r in rules}
        assert "total_amount_calculation" in names

    def test_sale_id_not_null_is_critical(self, quality_config):
        rules = quality_config["quality"]["rules"]["completeness"]
        sale_id_rule = next(r for r in rules if r["name"] == "sale_id_not_null")
        assert sale_id_rule["severity"] == "critical"

    def test_sale_id_unique_is_critical(self, quality_config):
        rules = quality_config["quality"]["rules"]["uniqueness"]
        rule = next(r for r in rules if r["name"] == "sale_id_unique")
        assert rule["severity"] == "critical"

    def test_all_five_quality_dimensions_covered(self, quality_config):
        dimensions = set(quality_config["quality"]["rules"].keys())
        expected = {"completeness", "uniqueness", "validity", "consistency", "accuracy"}
        assert expected.issubset(dimensions), f"Missing dimensions: {expected - dimensions}"


# ---------------------------------------------------------------------------
# 6. schedule.yaml tests (8 tests)
# ---------------------------------------------------------------------------

class TestScheduleConfig:
    """Validate scheduling configuration."""

    def test_has_schedule_key(self, schedule_config):
        assert "schedule" in schedule_config

    def test_frequency_daily(self, schedule_config):
        assert schedule_config["schedule"]["frequency"] == "daily"

    def test_start_time(self, schedule_config):
        assert schedule_config["schedule"]["start_time"] == "07:00"

    def test_timezone_utc(self, schedule_config):
        assert schedule_config["schedule"]["timezone"] == "UTC"

    def test_cron_expression(self, schedule_config):
        cron = schedule_config["schedule"]["cron_expression"]
        assert cron == "0 7 * * *"

    def test_retries_configured(self, schedule_config):
        retry = schedule_config["schedule"]["retry_policy"]
        assert retry["retries"] == 3

    def test_exponential_backoff(self, schedule_config):
        retry = schedule_config["schedule"]["retry_policy"]
        assert retry["retry_exponential_backoff"] is True

    def test_catchup_disabled(self, schedule_config):
        dag = schedule_config["schedule"]["dag_config"]
        assert dag["catchup"] is False


# ---------------------------------------------------------------------------
# 7. Cross-config consistency tests (5 tests)
# ---------------------------------------------------------------------------

class TestCrossConfigConsistency:
    """Validate consistency across config files."""

    def test_workload_name_consistent(self, source_config, semantic_config,
                                       transformations_config, quality_config,
                                       schedule_config):
        assert source_config["source"]["name"] == "daily_sales"
        assert semantic_config["semantic"]["workload"] == "daily_sales"
        assert transformations_config["transformations"]["workload"] == "daily_sales"
        assert quality_config["quality"]["workload"] == "daily_sales"
        assert schedule_config["schedule"]["workload"] == "daily_sales"

    def test_primary_key_in_source_matches_semantic(self, source_config, semantic_config):
        pk = source_config["source"]["primary_key"]
        columns = semantic_config["semantic"]["columns"]
        pk_col = next(c for c in columns if c["name"] == pk[0])
        assert pk_col.get("is_primary_key") is True

    def test_pii_columns_have_masking_rules(self, semantic_config, transformations_config):
        """Every PII column in semantic must have a masking rule in transformations."""
        columns = semantic_config["semantic"]["columns"]
        pii_cols = {c["name"] for c in columns if c.get("pii") is True}
        masking_rules = transformations_config["transformations"]["bronze_to_silver"]["pii_masking"]["rules"]
        masked_cols = {r["column"] for r in masking_rules}
        assert pii_cols.issubset(masked_cols), f"PII columns without masking: {pii_cols - masked_cols}"

    def test_quality_rule_columns_in_source_schema(self, source_config, quality_config):
        """All columns referenced in quality rules must exist in source schema."""
        schema_cols = {c["name"] for c in source_config["source"]["schema"]["columns"]}
        rules = quality_config["quality"]["rules"]
        for dimension, rule_list in rules.items():
            for rule in rule_list:
                if "column" in rule:
                    assert rule["column"] in schema_cols, \
                        f"Quality rule '{rule['name']}' references unknown column '{rule['column']}'"

    def test_dedup_key_matches_primary_key(self, source_config, transformations_config):
        pk = source_config["source"]["primary_key"]
        dedup_keys = transformations_config["transformations"]["bronze_to_silver"]["deduplication"]["key_columns"]
        assert set(pk) == set(dedup_keys)
